### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by xgaibtcgd** [andrevlima/economic-calendar-api#6]
Just loaded this up on a vanilla local centos/apache server and tried to view it as mentioned - but keep getting a 500 error.  logs are empty except for the access log just showing i'm trying to view the file with nothing else... any ideas?

**Comment by andrevlima** [comment]
It's strange, maybe it's something up to your local env... hard to say something without any logs

**Comment by xgaibtcgd** [comment]
Thanks, but this was 4 months ago and found a different solution
